"""empty message

Revision ID: 22fc57da867e
Revises: 2c1316eea5be
Create Date: 2015-12-01 18:35:46.013425

"""

# revision identifiers, used by Alembic.
revision = '22fc57da867e'
down_revision = '2c1316eea5be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('poster_name', sa.String()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'poster_name')
    ### end Alembic commands ###
