"""empty message

Revision ID: 23068abd2aff
Revises: 6586d640e92
Create Date: 2015-12-01 20:58:57.582143

"""

# revision identifiers, used by Alembic.
revision = '23068abd2aff'
down_revision = '6586d640e92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_comments')
    op.drop_table('u_comments')
    op.add_column('comments', sa.Column('parent', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent')
    op.create_table('u_comments',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], [u'comments.id'], name=u'u_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'users.id'], name=u'u_comments_user_id_fkey')
    )
    op.create_table('post_comments',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], [u'comments.id'], name=u'post_comments_comment_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], [u'posts.id'], name=u'post_comments_post_id_fkey')
    )
    ### end Alembic commands ###
