"""empty message

Revision ID: 238f1fd4774b
Revises: 36325d8aa1f4
Create Date: 2015-12-01 14:59:04.070044

"""

# revision identifiers, used by Alembic.
revision = '238f1fd4774b'
down_revision = '36325d8aa1f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('time_posted', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'time_posted')
    op.drop_constraint(None, 'group_posts', type_='foreignkey')
    op.create_foreign_key(u'group_posts_post_id_fkey', 'group_posts', 'users', ['post_id'], ['id'])
    ### end Alembic commands ###
