"""empty message

Revision ID: 28121aad4d31
Revises: 22fc57da867e
Create Date: 2015-12-01 19:58:20.073083

"""

# revision identifiers, used by Alembic.
revision = '28121aad4d31'
down_revision = '22fc57da867e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'post_comments_post_id_fkey', 'post_comments', type_='foreignkey')
    op.create_foreign_key(None, 'post_comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.create_foreign_key(u'post_comments_post_id_fkey', 'post_comments', 'posts', ['post_id'], ['id'])
    ### end Alembic commands ###
