"""empty message

Revision ID: 2ae6dcc61707
Revises: 56ca1ec32853
Create Date: 2015-12-01 22:05:10.530489

"""

# revision identifiers, used by Alembic.
revision = '2ae6dcc61707'
down_revision = '56ca1ec32853'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_post_likes')
    ### end Alembic commands ###
