"""empty message

Revision ID: 322692b412a1
Revises: 2ae6dcc61707
Create Date: 2015-12-01 22:11:04.368955

"""

# revision identifiers, used by Alembic.
revision = '322692b412a1'
down_revision = '2ae6dcc61707'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_posts', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('group_posts', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'group_posts_group_fkey', 'group_posts', type_='foreignkey')
    op.drop_constraint(u'group_posts_poster_fkey', 'group_posts', type_='foreignkey')
    op.create_foreign_key(None, 'group_posts', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'group_posts', 'groups', ['group_id'], ['id'])
    op.drop_column('group_posts', 'group')
    op.drop_column('group_posts', 'title')
    op.drop_column('group_posts', 'poster')
    op.drop_column('group_posts', 'time_posted')
    op.drop_column('group_posts', 'content')
    op.drop_column('group_posts', 'id')
    op.add_column('posts', sa.Column('group', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'groups', ['group'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'group')
    op.add_column('group_posts', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('group_posts', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('group_posts', sa.Column('time_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('group_posts', sa.Column('poster', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('group_posts', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('group_posts', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_posts', type_='foreignkey')
    op.drop_constraint(None, 'group_posts', type_='foreignkey')
    op.create_foreign_key(u'group_posts_poster_fkey', 'group_posts', 'users', ['poster'], ['id'])
    op.create_foreign_key(u'group_posts_group_fkey', 'group_posts', 'groups', ['group'], ['id'])
    op.drop_column('group_posts', 'post_id')
    op.drop_column('group_posts', 'group_id')
    ### end Alembic commands ###
