"""empty message

Revision ID: 36325d8aa1f4
Revises: cdf4fe506c9
Create Date: 2015-11-30 16:53:38.421592

"""

# revision identifiers, used by Alembic.
revision = '36325d8aa1f4'
down_revision = 'cdf4fe506c9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('description', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('private', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'private')
    op.drop_column('groups', 'description')
    ### end Alembic commands ###
