"""empty message

Revision ID: 3aa699fb8a0
Revises: 28121aad4d31
Create Date: 2015-12-01 20:05:31.941062

"""

# revision identifiers, used by Alembic.
revision = '3aa699fb8a0'
down_revision = '28121aad4d31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'post_comments_post_id_fkey', 'post_comments', type_='foreignkey')
    op.create_foreign_key(None, 'post_comments', 'posts', ['post_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.create_foreign_key(u'post_comments_post_id_fkey', 'post_comments', 'posts', ['post_id'], ['id'], ondelete=u'CASCADE')
    ### end Alembic commands ###
