"""empty message

Revision ID: 48923fd88d5b
Revises: 36c679d720d5
Create Date: 2015-11-29 19:37:19.925259

"""

# revision identifiers, used by Alembic.
revision = '48923fd88d5b'
down_revision = '36c679d720d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from', sa.Integer(), nullable=True),
    sa.Column('user_to', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_from'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    ### end Alembic commands ###
