"""empty message

Revision ID: 56ca1ec32853
Revises: 30d4d7e72636
Create Date: 2015-12-01 21:37:11.872995

"""

# revision identifiers, used by Alembic.
revision = '56ca1ec32853'
down_revision = '30d4d7e72636'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column(u'group_posts', sa.Column('content', sa.String(), nullable=False))
    op.add_column(u'group_posts', sa.Column('group', sa.Integer(), nullable=True))
    op.add_column(u'group_posts', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column(u'group_posts', sa.Column('poster', sa.Integer(), nullable=True))
    op.add_column(u'group_posts', sa.Column('time_posted', sa.DateTime(), nullable=True))
    op.add_column(u'group_posts', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint(u'group_posts_group_id_fkey', 'group_posts', type_='foreignkey')
    op.drop_constraint(u'group_posts_post_id_fkey', 'group_posts', type_='foreignkey')
    op.create_foreign_key(None, 'group_posts', 'groups', ['group'], ['id'])
    op.create_foreign_key(None, 'group_posts', 'users', ['poster'], ['id'])
    op.drop_column(u'group_posts', 'post_id')
    op.drop_column(u'group_posts', 'group_id')
    op.drop_constraint(u'posts_group_fkey', 'posts', type_='foreignkey')
    op.drop_column(u'posts', 'group')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column('group', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'posts_group_fkey', 'posts', 'groups', ['group'], ['id'])
    op.add_column(u'group_posts', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'group_posts', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'group_posts', type_='foreignkey')
    op.drop_constraint(None, 'group_posts', type_='foreignkey')
    op.create_foreign_key(u'group_posts_post_id_fkey', 'group_posts', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(u'group_posts_group_id_fkey', 'group_posts', 'groups', ['group_id'], ['id'])
    op.drop_column(u'group_posts', 'title')
    op.drop_column(u'group_posts', 'time_posted')
    op.drop_column(u'group_posts', 'poster')
    op.drop_column(u'group_posts', 'id')
    op.drop_column(u'group_posts', 'group')
    op.drop_column(u'group_posts', 'content')
    op.drop_table('group_post_likes')
    ### end Alembic commands ###
