"""empty message

Revision ID: 8289101ee1d
Revises: 8cc0bb95abc
Create Date: 2015-12-01 22:40:38.579031

"""

# revision identifiers, used by Alembic.
revision = '8289101ee1d'
down_revision = '8cc0bb95abc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'comments_parent_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['parent'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(u'comments_parent_fkey', 'comments', 'comments', ['parent'], ['id'])
    ### end Alembic commands ###
