"""empty message

Revision ID: 8cc0bb95abc
Revises: 322692b412a1
Create Date: 2015-12-01 22:19:34.034562

"""

# revision identifiers, used by Alembic.
revision = '8cc0bb95abc'
down_revision = '322692b412a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poster_name', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'poster_name')
    ### end Alembic commands ###
